server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/** , /auth/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/**
        - id: REQUEST-SERVICE
          uri: lb://REQUEST-SERVICE
          predicates:
            - Path=/request/**
  #Adding config-Server
  config:
    import: optional:configserver:http://localhost:8085/


