
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SaurabhMaurya9695/Config-Server
          clone-on-start: true
server:
  port: 8085
